### ISSUE TITLE
XMLSerializer#printStringMap(label, map, out) issue

### ISSUE THREAD

**Issue by JohannesOehm** [openEHR/java-libs#30]
Hello,

I'm trying to serialize my archetype as XML. When I have an archetype with an description like this:

    description
        original_author = <
            ["date"] = <"2015-01-01">
            ["name"] = <"Sample Author">
            ["organisation"] = <"Sample Organisation">
            ["email"] = <"sample@sample.com">
        >

it gets printed in the XML like this:

    <original_author id="date" />
    <original_author id="name" />
    <original_author id="organisation" />
    <original_author id="email" />

when it should be printed like this:

    <original_author id="date">2015-01-01</original_author>
    <original_author id="name">Sample Author</original_author>
    [...]

The issue is very likely located inside the `org.openehr.am.serialize.XMLSerializer#printStringMap`-method:

```java
    private void printStringMap(String label, Map<String, String> map, Element out) {

        if(map != null && !map.isEmpty()) {
            for(Map.Entry <String, String> entry : map.entrySet()) {
                Element elm = new Element(label, defaultNamespace);
                out.getChildren().add(elm);
                elm.setAttribute("id", entry.getKey());
                if (entry.getValue() != null) {
                    elm.setText(map.get(entry.getValue()));
                }
            }
        }
    }
```

It looks like `map.get(...)`-call was accidently used in `elm.setText(map.get(entry.getValue())`. Please fix!

**Comment by gardes** [comment]
Hi

Agree with your fix – but as far as I can see, this has been fixed on 11-Jan-2018 already, so you should be fine if you grab the latest version?

Regards, Sebastian

Von: Johannes Oehm <notifications@github.com>
Gesendet: Montag, 4. November 2019 09:50
An: openEHR/java-libs <java-libs@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [openEHR/java-libs] XMLSerializer#printStringMap(label, map, out) issue (#30)


Hello,

I'm trying to serialize my archetype as XML. When I have an archetype with an description like this:

description

    original_author = <

        ["date"] = <"2015-01-01">

        ["name"] = <"Sample Author">

        ["organisation"] = <"Sample Organisation">

        ["email"] = <"sample@sample.com<mailto:sample@sample.com>">

    >

it gets printed in the XML like this:

<original_author id="date" />

<original_author id="name" />

<original_author id="organisation" />

<original_author id="email" />

when it should be printed like this:

<original_author id="date">2015-01-01</original_author>

<original_author id="name">Sample Author</original_author>

[...]

The issue is very likely located inside the org.openehr.am.serialize.XMLSerializer#printStringMap-method:

    private void printStringMap(String label, Map<String, String> map, Element out) {



        if(map != null && !map.isEmpty()) {

            for(Map.Entry <String, String> entry : map.entrySet()) {

                Element elm = new Element(label, defaultNamespace);

                out.getChildren().add(elm);

                elm.setAttribute("id", entry.getKey());

                if (entry.getValue() != null) {

                    elm.setText(map.get(entry.getValue()));

                }

            }

        }

    }

It looks like map.get(...)-call was accidently used in elm.setText(map.get(entry.getValue()). Please fix!

**Comment by JohannesOehm** [comment]
Ah okay, I haven't sawn that. I installed the latest version from the GitHub to my local Maven Repository, and now it works. Thank you!
